language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
  - '7'
  - '8'
  - 'node'
before_script:
  - npm prune && npm cache clean
script:
  - npm run test:prod && npm run build
after_success:
  - npm run report-coverage
#  - npm run semantic-release

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: generated/docs
  github_token: $GITHUB_TOKEN
  on:
    branch: master
